### ISSUE TITLE
Unable to compute a SPARQL selection against WPFR

### ISSUE THREAD

**Issue by kelson42** [openzim/wp1#556] opened 2022-12-25 10:22 UTC
I have a SPARQL selection: https://query.wikidata.org/index.html#SELECT%20%3Fmuseum%20%3Farticle%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22fr%22.%20%7D%0A%20%20%3Fmuseum%20%28wdt%3AP195%2Fwdt%3AP361%29%20wd%3AQ1429003.%0A%20%20%7B%20%3Farticle%20schema%3Aabout%20%3Fmuseum.%20%3Farticle%20schema%3AisPartOf%20%3Chttps%3A%2F%2Ffr.wikipedia.org%2F%3E.%20%7D%0A%7D

And a WP1 SPARQL selection:
![image](https://user-images.githubusercontent.com/1029718/209464230-d68e5de3-0343-476e-a050-38fee58ca1a0.png)

But, although Wikidata delivers the result within a few seconds, after a minutes of loading WP1 generates and error:
![image](https://user-images.githubusercontent.com/1029718/209464261-90f28c36-9140-41f3-98b0-bea9fb6d2864.png)

I would expect to work and I don't understand why it fails actually.

**Comment by audiodude** [comment] 2022-12-26 19:36
The problem here is that the query variable is wrong. The query contains an `?article` subject, but it's really a `url`, the URL on English Wikipedia. The SPARQL Builder API expects the query variable to refer to the subject being selected, in this case the `?topic` query variable. So it should work if you use the same query but use `?topic` as the query variable, in the bottom text box. Tried that and it works.

I don't think we can auto-detect when the user has incorrectly identified the wrong thing in their query as `?article`, or when the query variable doesn't refer to the proper subject, but we can certainly do a better job when the query returns zero results which is ultimately the case in this situation. Perhaps we can offer guidance in an error message about checking that the selected query variable refers to a Wikidata subject (something with a QID).

**Comment by kelson42** [comment] 2022-12-26 20:16
@audiodude How WP1 know that the values corresponding to a variable are wrong (here URLs)? Why is this tested at all?

**Comment by kelson42** [comment] 2022-12-26 20:16
@audiodude How WP1 know that the values corresponding to a variable are wrong (here URLs)? Why is this tested at all?

**Comment by audiodude** [comment] 2022-12-26 20:18
Sorry I responded to this wrong issue! This is a comment for #555

**Comment by audiodude** [comment] 2022-12-26 20:32
Oh but yes, this query has the same problem. It uses the query variable `?article` to refer to the URL that it's selecting with`schema:about` instead of the subjects/entities that are being selected, which are referred to as `?museum` so the query variable for the builder should be `?museum`.

I don't know why in this case Wikidata is returning a 500 instead of an empty result set though, will look more into it.

In general, the way the SPARQL Builder creates article lists out of SPARQL queries is by adding a "shadow" variable to the query, where it does the same thing that is being done for `?article` in this query. So if you have a query for selecting bands like:

```
#Rock bands that start with "M"
SELECT ?band ?bandLabel
WHERE
{
  ?band wdt:P31 wd:Q5741069 .
        ?band rdfs:label ?bandLabel .
  FILTER(LANG(?bandLabel) = "en") .
  FILTER(STRSTARTS(?bandLabel, 'M')) .
}
```

It gets rewritten as:

```
#Rock bands that start with "M"
SELECT ?band ?bandLabel
WHERE
{
  ?band wdt:P31 wd:Q5741069 .
        ?band rdfs:label ?bandLabel .
          OPTIONAL {
        ?_wp1_0 schema:isPartOf 'https://en.wikipedia.org'.
        ?_wp1_0 schema:about ?band
      }
  FILTER(LANG(?bandLabel) = "en") .
  FILTER(STRSTARTS(?bandLabel, 'M')) .
}
```

And then we look at the bindings for `?_wp1_0` for finding the article URLs and extracting the article names.

This was a design choice. We could have alternately required users to construct queries that had article URL selection built into them, such as these two examples we're working with. That wouldn't have worked well with our existing project selection mechanism though. And the user would still need to instruct the service which query variable refers to the URL when creating the Builder.

**Comment by kelson42** [comment] 2022-12-26 20:50
If I understand right, the current system:
* requires to select and have a query variable pointing to a column with values like wd:... identifying items in Wikidata
* WP1 modifies the request to subfilter on items with Wikipedia articles
* For each item you look to find the WP article ids

The system offers the advantage that the user has to focus only on the topic part and not at all on Wikipedia stuff. The inconvenient is that it has to be pretty robust (sounds a bit fragile to me).

In our example, actually all the job is already done by the original request (because URLs of WP articles are already there). My first idea is that WP1 would need this kind of request and that WP1 would not be that smart.

I'm not sure what is the best approach, but the kind of values expected should be clearly explained and tested. If users gives a query variable which delivers URLs, then this is not something like wd:... and we can direcly display an helpful error message IMO.

**Comment by audiodude** [comment] 2022-12-26 21:06
Your understanding is mostly correct. The only thing is that WP1 isn't "subfiltering", it's doing a LEFT JOIN, so it will run the entire query but only output article ids where there are URLs (aka where articles exist in the project specified by the user).

> The inconvenient is that it has to be pretty robust (sounds a bit fragile to me).

Yes I am no expert in SPARQL schemas and made my best effort at rewriting the query based on my limited knowledge. I tried a few types of queries with UNIONs and FILTERs but I'm not confident that I got it all.

> In our example, actually all the job is already done by the original request (because URLs of WP articles are already there). My first idea is that WP1 would need this kind of request and that WP1 would not be that smart.

Yes this is one option, though as I mentioned, the user would still need to indicate to the system which query variable is the one that represents the URLs. We'd also have the problem that the user would need to make sure that the project they select on the builder creation screen (fr.wikipedia.org for example) corresponds to the URL they are using `schema:about` with in the query. Otherwise, we might find entities that have English Wikipedia articles (specified in the query), then attempt to create a ZIM file from French Wikipedia (specified on the Builder creation page), so the article names/ids would possibly be wrong.

> but the kind of values expected should be clearly explained and tested.

Yeah sure, except that there were no sample queries or use cases for this system provided when it was designed and built. Give me 25 or so sample queries and I can design and build a system that works for all of them, then we can deal with outliers as they crop up.

> If users gives a query variable which delivers URLs, then this is not something like wd:... and we can direcly display an helpful error message IMO.

Perhaps we can instruct the user that they have to query for the URLs themselves, or give them the option of using the automatic query rewriter (with the knowledge that it might fail and explaining when it does). We could detect which variable contains the URLs by string matching against the query results, and this would have the added benefit that we could solve the problem mentioned above. For example, if the user selects "fr.wikipedia.org" as the project, but the results have English URLs we could raise an error. Or we could get rid of project selection altogether and simply infer it from the URLs that are returned by the query (though it would still need to be specified for any "auto" rewriter).

**Comment by kelson42** [comment] 2022-12-31 15:49
I have change the SPARQL to:
```
SELECT ?item WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "fr". }
  ?item (wdt:P195/wdt:P361) wd:Q1429003.
}
```

And it works now, but I have found an other problem. See #568 

Tha said I wonder if we should really keep this ticket open considering that you have open #560.

@audiodude Should we close it?

**Comment by audiodude** [comment] 2022-12-31 16:04
Yes we can close this.

To be clear, the root cause of this issue is "query rewriting not working".

**Closed by audiodude** 2022-12-31 16:04 UTC
Labels: bug, question
